name:                tinbox
version:             0.1.0.0
homepage:            https://gitlab.com/tsaron/tinbox#readme
license:             AllRightsReserved
author:              Arewa Olakunle
maintainer:          arewa.olakunle@gmail.com
copyright:           Arewa Olakunle
category:            web
extra-source-files:
- README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Widentities
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fhide-source-paths

dependencies:
  - base >= 4.7 && < 5
  - blaze-html
  - blaze-markup
  - cookie
  - digestive-functors
  - digestive-functors-scotty
  - exceptions
  - hedis
  - opaleye
  - profunctors
  - product-profunctors
  - postgresql-simple
  - scotty
  - scotty-cookie
  - split
  - template-haskell
  - text
  - wai
  - wai-extra
  - warp

library:
  source-dirs: src
  exposed-modules:
    - Routes

executables:
  tinbox:
    source-dirs: app
    main: Main.hs
    dependencies:
      - tinbox
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - base
      - hspec
      - hspec-wai
      - tinbox
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N


